### ISSUE TITLE
Página e feed do Planet não estão atualizando

### ISSUE THREAD

**Issue by paulohrpinheiro** [pythonbrasil/planet#10]
Salve! Percebi que a página e o feed não estão sendo atualizados desde 05/Jun/2018, apesar de existirem textos novos nos blogs. Também aquela página esta direcionando para um repositório antigo de gerenciamento.

Tentei algum contato no irc mas não obtive resposta. Eu posso ajudar de alguma forma?

Obrigado.

**Comment by humrochagf** [comment]
Opa,

Iniciei o processo de recuperação do planet, ele já voltou a atualizar se puder verificar se está funcionando para vc
