### ISSUE TITLE
Feed agregando comentários do medium

### ISSUE THREAD

**Issue by rochacbruno** [pythonbrasil/planet#5]
Percebi hoje que o feed do @avelino está coletando comentários do Medium ao invés de posts relacionados (taggeados ou categorizados) a Python.

https://wiki.python.org.br/planet/

![screenshot_2017-10-18_02-13-42](https://user-images.githubusercontent.com/458654/31700733-2a0ccc56-b3aa-11e7-972a-57d929563f1d.png)
![screenshot_2017-10-18_02-13-21](https://user-images.githubusercontent.com/458654/31700734-2a3ae28a-b3aa-11e7-80fd-fba33b4948a2.png)
![screenshot_2017-10-18_02-13-09](https://user-images.githubusercontent.com/458654/31700735-2a6997d8-b3aa-11e7-932a-502f056965fb.png)

Não sei dizer se é um problema do medium ou do feedburner mas de qualquer modo comentários não deveriam ser publicados no planet mas sim apenas posts relacionados a Python.

@avelino pode nos ajudar a resolver esse problema? ou fornecer uma URL de feed que seja diretamente categorizada com Python?

https://github.com/pythonbrasil/planet/blob/master/planet.conf#L222

Valeu! :)

**Comment by humrochagf** [comment]
Opa,

@rochacbruno tô dando uma geral aqui que o feed tinha parado, não tem mais a referência para este blog, depois se puder dar uma olhadinha se tem mais alguma coisa pendente por aqui antes de finalizar esta issue
